
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    container_name: api
    depends_on:
      - mongodb
    build: 
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env   

  ui:
    container_name: frontend
    build:
      context: frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    

volumes:
  mongo_volume: